### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by amelon**
hi @chrisjpowers,

thanks for your update and now it works on windows :)
Nice job.
I'm really excited to see css version.

I had a really bad experience with jquery file and burito function (waiting more than 15 seconds for result).
I put a test to bypass burito if no stripFunctions provided.

### CODE REVIEW

**Comment by chrisjpowers** [comment]
Awesome! Thanks for the heads up on Burrito, btw, that's good to know, I hadn't tried it with jQuery yet. I'm going to update the code so that each source file is grep-ed for the stripped function, and Burrito is only used if the function name is in the given file.

The dependency and CSS features are already in master (and in the v0.2.0 release), so I'm going to merge this directly into master, thanks again for the Windows help!

**Comment by amelon** [comment]
Do you have any doc or exemple for css?
I'd like to know how do you handle node_modules library with air-drop (exemple or doc would be welcome).

Thanks.

**Comment by chrisjpowers** [comment]
Take a look near the bottom I the README in Master, it has some documentation on using AirDrop for CSS. The nicest feature (I think) is that AirDrop replaces @import directives with the inlined file contents, so you can treat CSS files as dependencies.

Re: node_modules, you can just require the module in your code and AirDrop will find the directory in node_modules, read package.json to find the "main" file, and require it And any dependencies. For example, require("underscore") works out of the box. However, this assumes that the module doesn't use anything Node specific.

**Comment by amelon** [comment]
Sorry for my question I hadn't read your new master read.me. (I focused on dependencies branch).

That's sound excellent.
I will test every thing pretty soon.

Thanks

**Comment by chrisjpowers** [comment]
No worry, thanks again for your help. You also might be interested that I just pushed up the `air-drop` shell command to master, which allows you to use AirDrop to package your assets in non-Node.js projects.

**Pull request merged**
